version: '3'
services:
  drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: drupal
      MYSQL_USER: root
      MYSQL_PASSWORD: example

  database:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8000:80"
