version: '3'

services:
  drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal

volumes:
  drupal_data:
